/*
 * EEPROM_Config.h
 *
 *  Created on: Oct 10, 2021
 *      Author: Lenovo
 */

#ifndef INTERNAL_EEPROM_CONFIG_H_
#define INTERNAL_EEPROM_CONFIG_H_

/*	INTERNAL_EEPROM_INTERRUPT OPTIONS
 * 1-INTERNAL_EEPROM_INTERRUPT_DISABLE
 * 2-INTERNAL_EEPROM_INTERRUPT_ENABLE*/
#define INTERNAL_EEPROM_INTERRUPT	INTERNAL_EEPROM_INTERRUPT_DISABLE


#endif /* INTERNAL_EEPROM_CONFIG_H_ */
