/*
 * Timer_Config.h
 *
 *  Created on: Sep 19, 2021
 *      Author: Lenovo
 */

#ifndef TIMER_CONFIG_H_
#define TIMER_CONFIG_H_

/*Watch Dog Prescaler Options
 * 1-WATCHDOG_PRESCALER_16K
 * 2-WATCHDOG_PRESCALER_32K
 * 3-WATCHDOG_PRESCALER_64K
 * 4-WATCHDOG_PRESCALER_128K
 * 5-WATCHDOG_PRESCALER_256K
 * 6-WATCHDOG_PRESCALER_512K
 * 7-WATCHDOG_PRESCALER_1024K
 * 8-WATCHDOG_PRESCALER_2048K
 */

#define WATCHDOG_PRESCALER_MODE		WATCHDOG_PRESCALER_1024K



/*****************	TIMER 0		*****************/


/* Timer0 Mode Options
 * 1-TIMER0_NORMAL_MODE
 * 2-TIMER0_CTC_MODE
 * 3-TIMER0_PWM_PHASECORRECT_MODE
 * 4-TIMER0_PWM_FAST_MODE
 */
#define TIMER0_MODE		TIMER0_CTC_MODE

/*	Timer0 Prescaler Options
 * 1-TIMER0_NO_PRESCALER
 * 2-TIMER0_8_PRESCALER
 * 3-TIMER0_64_PRESCALER
 * 4-TIMER0_256_PRESCALER
 * 5-TIMER0_1024_PRESCALER
 * 6-TIMER0_EXTERNAL_SOURCE_FALLING
 * 7-TIMER0_EXTERNAL_SOURCE_RISING
 */
#define TIMER0_PRESCALER	TIMER0_64_PRESCALER

#define TIMER0_PRELOAD      0
/* OC00 PIN MODE Options in CTC MODE
 * 1-OC0_PIN_DISCONNECTED
 * 2-OC0_PIN_TOGGLE
 * 3-OC0_PIN_CLEAR
 * 4-OC0_PIN_SET
 */
/* OC00 PIN MODE Options in PHASE CORRECT
 * 1-OC0_PIN_DISCONNECTED
 * 2-OC0_PIN_TOGGLE
 * 3-OC0_PIN_CLEAR
 * 4-OC0_PIN_SET
 */
/* OC00 PIN MODE Options in FAST MODE
 * 1-OC0_PIN_DISCONNECTED
 * 2-OC0_PIN_TOGGLE
 * 3-OC0_PIN_CLEAR
 * 4-OC0_PIN_SET
 */
#define OC0_PIN_MODE		OC0_PIN_DISCONNECTED
#define TIMER0_CTC			250//156


/*****************	TIMER 1		*****************/


/* Timer1 Mode Options
 * 1-TIMER1_NORMAL_MODE
 * 2-TIMER1_CTC_MODE
 * 3-TIMER1_PWM_PHASECORRECT_MODE
 * 4-TIMER1_PWM_FAST_MODE
 */
#define TIMER1_MODE		TIMER1_NORMAL_MODE

/*	Timer1 Prescaler Options
 * 1-TIMER1_NO_PRESCALER
 * 2-TIMER1_8_PRESCALER
 * 3-TIMER1_64_PRESCALER
 * 4-TIMER1_256_PRESCALER
 * 5-TIMER1_1024_PRESCALER
 * 6-TIMER1_EXTERNAL_SOURCE_FALLING
 * 7-TIMER1_EXTERNAL_SOURCE_RISING
 */
#define TIMER1_PRESCALER	TIMER1_8_PRESCALER


/* OC1 PIN MODE Options in non-PWM MODE
 * 1-OC1_PIN_DISCONNECTED
 * 2-OC1_PIN_TOGGLE
 * 3-OC1_PIN_CLEAR
 * 4-OC1_PIN_SET
 */
/* OC1 PIN MODE Options in PHASE CORRECT
 * 1-OC1_PIN_DISCONNECTED
 * 2-OC1_PIN_TOGGLE
 * 3-OC1_PIN_CLEAR
 * 4-OC1_PIN_SET
 */
/* OC1 PIN MODE Options in FAST MODE
 * 1-OC1_PIN_DISCONNECTED
 * 2-OC1_PIN_TOGGLE
 * 3-OC1_PIN_CLEAR
 * 4-OC1_PIN_SET
 */
#define OC1A_PIN_MODE		OC1_PIN_DISCONNECTED
#define OC1B_PIN_MODE		OC1_PIN_DISCONNECTED


/*****************	TIMER 2		*****************/


/* Timer2 Mode Options
 * 1-TIMER2_NORMAL_MODE
 * 2-TIMER2_CTC_MODE
 * 3-TIMER2_PWM_PHASECORRECT_MODE
 * 4-TIMER2_PWM_FAST_MODE
 */
#define TIMER2_MODE		TIMER2_PWM_FAST_MODE

/*	Timer2 Prescaler Options
 * 1-TIMER2_NO_PRESCALER
 * 2-TIMER2_8_PRESCALER
 * 3-TIMER2_32_PRESCALER
 * 4-TIMER2_64_PRESCALER
 * 5-TIMER2_128_PRESCALER
 * 6-TIMER2_256_PRESCALER
 * 7-TIMER2_1024_PRESCALER
 */
#define TIMER2_PRESCALER	TIMER2_1024_PRESCALER

#define TIMER2_PRELOAD      212
/* OC2 PIN MODE Options in CTC MODE
 * 1-OC2_PIN_DISCONNECTED
 * 2-OC2_PIN_TOGGLE
 * 3-OC2_PIN_CLEAR
 * 4-OC2_PIN_SET
 */
/* OC20 PIN MODE Options in PHASE CORRECT
 * 1-OC2_PIN_DISCONNECTED
 * 2-OC2_PIN_TOGGLE
 * 3-OC2_PIN_CLEAR
 * 4-OC2_PIN_SET
 */
/* OC20 PIN MODE Options in FAST MODE
 * 1-OC2_PIN_DISCONNECTED
 * 2-OC2_PIN_TOGGLE
 * 3-OC2_PIN_CLEAR
 * 4-OC2_PIN_SET
 */

#define OC2_PIN_MODE		OC2_PIN_DISCONNECTED
#define TIMER2_CTC			156


#endif /* TIMER_CONFIG_H_ */
